version: '3.8'
volumes:
  pg_project:
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
     - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  typescript-backend-template:
    image: node:14-alpine
    environment:
      - PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    working_dir: /opt/typescript-backend-template
    volumes:
      - ".:/opt/typescript-backend-template"
    command: npm run dev:seed

