version: '3.8'
volumes:
  pg_project:
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=pg_db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
     - pg_project:/var/lib/postgresql/data
    ports:
      - 5432:5432
  typescript-backend-template:
    image: node:14-alpine
    environment:
      - SERVER_PORT=5000
      - POSTGRES_HOST=pg_db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    ports:
      - 5000:5000
    working_dir: /opt/typescript-backend-template
    volumes:
      - ".:/opt/typescript-backend-template"
    command: npm run dev:docker

